### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mkaito** [themoken/canto-next#31]
This happens once in a while:

```
Traceback (most recent call last):
  File "/usr/bin/canto-remote", line 7, in <module>
    c = CantoRemote()
  File "/usr/lib/python3.5/site-packages/canto_next/remote.py", line 95, in __init__
    self.handle_args()
  File "/usr/lib/python3.5/site-packages/canto_next/remote.py", line 573, in handle_args
    r = func()
  File "/usr/lib/python3.5/site-packages/canto_next/remote.py", line 549, in cmd_status
    print("%s" % sum([self._numstate(tag, state) for tag in t ]))
TypeError: 'NoneType' object is not iterable
```

Which causes some issues when using `canto-remote status` in a conky field. Conky itself doesn't mind, but i3bar crashes with something about incorrect JSON.

**Comment by themoken** [comment]
I think I just fixed this in git after a quick reproduction, so try the latest and let me know if you see it again.

That said, you should probably figure out a way to sanitize the output for i3bar because the remote spitting out a traceback is definitely still *possible* if something bad happens (like in this case, the daemon died in the middle of a request).
